name: Build Android APK from PWA Builder API

on:
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. PWA Builder APIを呼び出して、指定したURLをアプリ化
    - name: Call PWA Builder API for Android APK
      run: |
        curl -X POST "https://www.pwabuilder.com/api/generate" \
        -H "Content-Type: application/json" \
        -d '{
              "url": "https://pwaserve.com/",
              "platforms": ["android"]
            }' \
        -o pwa_builder_response.json

    # 3. レスポンスの中身を確認する (デバッグ用)
    - name: Print API response
      run: |
        cat pwa_builder_response.json

    # 4. レスポンスからAPKファイルのダウンロードURLを抽出
    - name: Extract APK download link from response
      run: |
        apk_url=$(cat pwa_builder_response.json | jq -r '.platforms.android.package.url')
        if [ -z "$apk_url" ]; then
          echo "Failed to extract APK URL. Please check the API response."
          exit 1
        fi
        echo "APK Download URL: $apk_url"

    # 5. APKをダウンロード
    - name: Download APK
      run: |
        apk_url=$(cat pwa_builder_response.json | jq -r '.platforms.android.package.url')
        curl -L "$apk_url" -o android_app.apk

    # 6. ダウンロードしたAPKをアーティファクトとして保存
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: android_app
        path: android_app.apk
